"""
utilities/email_service.py
Transactional email via SendGrid — replaces raw smtplib + plaintext credentials.
Validates recipient address before sending to prevent header injection.
"""
from __future__ import annotations

import base64
import os
from email_validator import validate_email, EmailNotValidError
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import (
    Mail, Attachment, FileContent, FileName, FileType, Disposition
)

from core.config import get_settings
from utilities.logger import get_logger

log = get_logger(__name__)
settings = get_settings()


class EmailValidationError(ValueError):
    pass


def _validate_recipient(email: str) -> str:
    """Validate and normalise email address. Raises EmailValidationError on failure."""
    try:
        result = validate_email(email, check_deliverability=False)
        return result.normalized
    except EmailNotValidError as e:
        raise EmailValidationError(f"Invalid recipient email: {e}") from e


def send_proposal_email(
    to_email: str,
    customer_name: str,
    pdf_path: str,
) -> bool:
    """
    Send the investment proposal PDF to the client via SendGrid.
    Returns True on success, False on failure (logs error, never raises).
    """
    if not settings.sendgrid_api_key:
        log.warning("SENDGRID_API_KEY not set — email not sent")
        return False

    try:
        recipient = _validate_recipient(to_email)
    except EmailValidationError as e:
        log.error("Email send aborted: %s", e)
        raise

    try:
        with open(pdf_path, "rb") as f:
            encoded_pdf = base64.b64encode(f.read()).decode()
    except OSError as e:
        log.error("Could not read PDF for email attachment: %s", e)
        return False

    message = Mail(
        from_email=settings.email_from,
        to_emails=recipient,
        subject=f"Your Investment Proposal — {customer_name}",
        html_content=f"""
        <p>Dear {customer_name},</p>
        <p>Please find your personalised investment proposal attached.</p>
        <p><em>This proposal is generated by an AI system and is for informational
        purposes only. It does not constitute regulated financial advice under
        SEBI (Investment Advisers) Regulations, 2013.</em></p>
        <p>Kind regards,<br>Investment Advisory Team</p>
        """,
    )

    attachment = Attachment(
        FileContent(encoded_pdf),
        FileName("investment_proposal.pdf"),
        FileType("application/pdf"),
        Disposition("attachment"),
    )
    message.attachment = attachment

    try:
        sg = SendGridAPIClient(settings.sendgrid_api_key)
        response = sg.send(message)
        log.info("Email sent to %s — status %d", recipient, response.status_code)
        return response.status_code in (200, 202)
    except Exception as e:
        log.error("SendGrid send failed: %s", e)
        return False
