"""
models/schemas.py
Pydantic v2 schemas used throughout the application:
  - InvestmentDocument   : validated RAG document
  - CustomerProfile      : structured client profile
  - AssetAllocation      : single allocation row
  - InvestmentProposal   : structured LLM output (with_structured_output)
  - ProposalRequest      : API/UI input model
"""
from __future__ import annotations
from typing import List, Literal, Optional
from datetime import datetime
from pydantic import BaseModel, Field, field_validator, EmailStr


# ---------------------------------------------------------------------------
# RAG document validation (replaces missing Pydantic usage in original code)
# ---------------------------------------------------------------------------

class InvestmentDocument(BaseModel):
    content: str = Field(min_length=10)
    source: str
    doc_type: Literal["pdf", "web", "past_proposal"]

    @field_validator("content")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        return v.strip()


# ---------------------------------------------------------------------------
# Customer profile
# ---------------------------------------------------------------------------

class CustomerProfileSchema(BaseModel):
    customer_id: str
    name: str
    email: EmailStr
    age: Optional[int] = Field(None, ge=18, le=100)
    annual_income_inr: Optional[float] = Field(None, ge=0)
    risk_appetite: Optional[Literal["Low", "Medium", "High"]] = None
    investment_horizon_years: Optional[int] = Field(None, ge=1, le=40)
    financial_goals: List[str] = Field(default_factory=list)
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# Proposal structured output — used with llm.with_structured_output()
# ---------------------------------------------------------------------------

class AssetAllocation(BaseModel):
    asset_class: str = Field(description="E.g. Large Cap Equity, Debt, Gold, REITs")
    percentage: float = Field(ge=0, le=100, description="Allocation percentage")
    rationale: str = Field(description="One-sentence rationale")
    suggested_instruments: List[str] = Field(
        default_factory=list,
        description="Specific fund names or instruments",
    )


class InvestmentProposal(BaseModel):
    customer_name: str
    prepared_date: str = Field(description="ISO date string")
    financial_health_score: int = Field(ge=1, le=10, description="1=poor, 10=excellent")
    risk_appetite: Literal["Low", "Medium", "High"]
    investment_horizon_years: int = Field(ge=1, le=40)
    monthly_investable_surplus_inr: Optional[float] = None
    asset_allocation: List[AssetAllocation] = Field(
        description="Must sum to 100%"
    )
    recommended_products: List[str]
    expected_annual_return_pct: float = Field(ge=0, le=50)
    key_risks: List[str]
    mitigation_strategies: List[str]
    next_review_months: int = Field(default=6)
    executive_summary: str
    disclaimer: str = (
        "This proposal is generated by an AI system and is for informational "
        "purposes only. It does not constitute regulated financial advice under "
        "SEBI (Investment Advisers) Regulations, 2013. Please consult a SEBI-registered "
        "investment adviser before making any investment decisions."
    )

    @field_validator("asset_allocation")
    @classmethod
    def allocations_sum_to_100(cls, v: List[AssetAllocation]) -> List[AssetAllocation]:
        total = sum(a.percentage for a in v)
        if not (99.0 <= total <= 101.0):
            raise ValueError(f"Asset allocations must sum to ~100%, got {total:.1f}%")
        return v


# ---------------------------------------------------------------------------
# UI / API input
# ---------------------------------------------------------------------------

class ProposalRequest(BaseModel):
    customer_id: str
    question: str = Field(
        default="Generate a comprehensive investment proposal",
        min_length=5,
    )
    chunk_size: int = Field(default=1000, ge=200, le=3000)
    chunk_overlap: int = Field(default=200, ge=0, le=500)
    top_k: int = Field(default=5, ge=2, le=10)
